---
- name: Support Docker deployment
  hosts: all
  become: yes
  vars:
    log_file: "/var/log/docker_install_ansible.log"
    ansible_python_interpreter: /usr/bin/python

  tasks:     
    - name: Clean yum cache and add Docker repo
      command: "{{ item }}"
      loop:
        - yum clean all
        - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      changed_when: false

    - name: Install Docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      register: docker_install

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes
      changed_when: false

    - name: Check for existing containers
      shell: docker ps -aq
      register: container_ids
      changed_when: false

    - name: Delete all containers
      shell: docker rm -f $(docker ps -aq)
      when: container_ids.stdout != ""
      ignore_errors: yes

    - name: Check for existing images
      shell: docker images -q
      register: image_ids
      changed_when: false

    - name: Delete all images
      shell: docker rmi -f $(docker images -q)
      when: image_ids.stdout != ""
      ignore_errors: yes

      
    - name: Verify Docker is running
      command: docker run --rm -d -p 80:4200 --name web evgeny412/payoneer-exam:master
      register: docker_verify
      changed_when: false

    - name: Log installation results
      copy:
        content: |
          Docker installation: {{ docker_install.changed | ternary('changed', 'unchanged') }}
          Docker verification: {{ docker_verify.rc == 0 | ternary('successful', 'failed') }}
          {{ docker_verify.stdout }}
        dest: "{{ log_file }}"
      changed_when: false

    - name: Display log contents
      command: cat {{ log_file }}
      register: log_contents
      changed_when: false

    - name: Show log
      debug:
        msg: "{{ log_contents.stdout_lines }}"
