name: CD Pipeline - Deploy with Ansible

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate Ansible Inventory File
        run: |
          echo "[centos]" > payoneer/ansible/inventory.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> payoneer/ansible/inventory.ini

      - name: Build Docker Image
        run: docker build -t jenia-keidar/payoneer-app ./payoneer

      - name: Save Docker Image to File
        run: docker save jenia-keidar/payoneer-app -o jenia-keidar/payoneer-app.tar

      - name: Transfer Docker Image to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa jenia-keidar/payoneer-app.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/centos/

      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: payoneer/ansible/ansible.yml
          inventory: payoneer/ansible/inventory.ini
          key: ~/.ssh/id_rsa

      - name: Load Docker Image and Run Container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker load -i /home/centos/jenia-keidar/payoneer-app.tar && \
          docker run -d --name payoneer-app -p 80:80 jenia-keidar/payoneer-app"
