name: cd

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh  
          echo "${{ secrets.EC2_SSH_KEY }}" > private.pem  
          chmod 600 private.pem 
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts


      - name: Build Docker image with a specific tag
        run: docker build -t jenia-keidar/payoneer-app:latest ./payoneer

      - name: Generate Ansible Inventory Inline
        run: |
          echo "[all]" > inventory.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=private.pem ansible_python_interpreter=/usr/bin/python" >> inventory.ini
          cat ./inventory.ini

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Python on GitHub Actions Runner
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Run Ansible Playbook Manually
        run: |
          ansible-playbook -i inventory.ini payoneer/ansible/ansible.yml


      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: payoneer/ansible/ansible.yml
          inventory: inventory.ini

      - name: Deploy Docker Container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker run -d --name payoneer-app -p 4200:4200 jenia-keidar/payoneer-app:latest"
