name: CD Pipeline - Deploy Docker Image

on:
  push:
    branches:
      - master


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate Ansible Inventory Inline
        run: |
          echo "[centos]" > inventory.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini

      - name: Build Docker image with a specific tag
        run: docker build -t jenia-keidar/payoneer-app:latest ./payoneer

      - name: Save Docker Image as a Tar File
        run: docker save -o jenia-keidar-payoneer-app.tar jenia-keidar/payoneer-app:latest

      - name: Transfer Docker Image to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa jenia-keidar-payoneer-app.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/centos/

      - name: Run Ansible Playbook for Docker Deployment
        run: |
          ansible-playbook -i inventory.ini payoneer/ansible/ansible.yml --private-key ~/.ssh/id_rsa

      - name: Deploy Docker Container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker load -i /home/centos/jenia-keidar-payoneer-app.tar && \
          if [ \$(docker ps -aq -f name=payoneer-app) ]; then \
            docker stop payoneer-app && docker rm payoneer-app; \
          fi && \
          docker run -d --name payoneer-app -p 4200:4200 jenia-keidar/payoneer-app:latest"
