name: CD Pipeline - Deploy Docker Image to EC2

on:
  workflow_run:
    workflows: ["CI Pipeline - Build, Test, and Prepare"]
    types:
      - completed

jobs:
  cd-pipeline:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for deployment
        run: docker build -t payoneer-app ./payoneer

      - name: Save Docker image locally
        run: docker save -o payoneer-app.tar payoneer-app

      - name: Transfer Docker image to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no payoneer-app.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/centos/

      - name: Deploy Docker image on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker load -i /home/centos/payoneer-app.tar
            if [ "$(docker ps -aq -f name=payoneer-app)" ]; then
              docker stop payoneer-app
              docker rm payoneer-app
            fi
            docker run -d --name payoneer-app -p 80:80 payoneer-app
          EOF
