name: CD Pipeline - Push and Deploy Docker Image

on:
  workflow_run:
    workflows: ["CI Pipeline - Build and Tag Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Generate Ansible Inventory File
        run: |
          echo "[centos]" > payoneer/ansible/inventory.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> payoneer/ansible/inventory.ini

      - name: Build Docker image with a specific tag
        run: docker build -t jenia-keidar/payoneer-app:latest ./payoneer

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push jenia-keidar/payoneer-app:latest

      - name: Transfer Docker Image to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa jenia-keidar/payoneer-app.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/centos/

      - name: Run Ansible Playbook for Docker Deployment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: payoneer/ansible/ansible.yml
          inventory: payoneer/ansible/inventory.ini
          key: ~/.ssh/id_rsa

      - name: Deploy Docker Container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "docker pull jenia-keidar/payoneer-app:latest && \
          if [ \$(docker ps -aq -f name=payoneer-app) ]; then \
            docker stop payoneer-app && docker rm payoneer-app; \
          fi && \
          docker run -d --name payoneer-app -p 80:80 jenia-keidar/payoneer-app:latest"
