name: CI Pipeline - Build, Test, and Prepare

on:
  push:
    branches:
      - '*'   # Runs on push to any branch
  pull_request:
    branches:
      - '*'   # Runs on pull requests to any branch

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '18'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install project dependencies
        run: npm ci
        working-directory: ./payoneer

      - name: Build Angular application
        run: npm run build --if-present
        working-directory: ./payoneer

      - name: Run unit tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless
        working-directory: ./payoneer

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: angular-build
          path: |
            ./payoneer/dist/
            !./payoneer/dist/*.map
          retention-days: 5
