name: ci

on:
  push:
    branches:
      - '*'   # Runs on push to any branch except main
  pull_request:
    branches:
      - '*'   # Runs on pull requests to any branch

jobs:
  build-test-tag:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, 'retest')) ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'push')
    runs-on: ubuntu-latest
    env:
      RANDOM_TAG: ${{ github.sha }}  # Use commit SHA for a unique tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./payoneer

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./payoneer

      - name: Build Angular app
        run: ng build
        working-directory: ./payoneer

      - name: Run unit tests
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./payoneer

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: evgeny412/payoneer-exam

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./payoneer
          file: ./payoneer/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
