name: CI Pipeline

on:
  push:
    branches:
      - '*'   # Runs on push to any branch
  pull_request:
    branches:
      - '*'   # Runs on pull requests to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./payoneer

      - name: Build Angular App
        run: npm run build
        working-directory: ./payoneer

      - name: Run Tests
        run: npm test
        working-directory: ./payoneer
