name: CI Pipeline - Build, Test, and Tag Image

on:
  push:
    branches:
      - '*'   # Runs on push to any branch except main
  pull_request:
    branches:
      - '*'   # Runs on pull requests to any branch

jobs:
  build-test-tag:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, 'retest')) ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'push')
    runs-on: ubuntu-latest
    env:
      RANDOM_TAG: ${{ github.sha }}  # Use commit SHA for a unique tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./payoneer

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./payoneer

      - name: Build Angular app
        run: ng build
        working-directory: ./payoneer

      - name: Run unit tests
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./payoneer

      - name: Build Docker image and tag it
        run: docker build -t payoneer-app:${{ env.RANDOM_TAG }} ./payoneer

      - name: Save Docker image locally for testing
        run: docker save -o payoneer-app-${{ env.RANDOM_TAG }}.tar payoneer-app:${{ env.RANDOM_TAG }}

      - name: Upload image artifact (optional for later use)
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-${{ env.RANDOM_TAG }}
          path: payoneer-app-${{ env.RANDOM_TAG }}.tar
